services:
  db:
    image: postgres:17.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: find_my_club_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

#  redis:
#    image: redis:7-alpine
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle exec rails db:create db:migrate && rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/find_my_club_development
#      REDIS_URL: redis://redis:6379/0
      RAILS_MAX_THREADS: 5
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
      - rails_cache:/rails/tmp/cache
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
#      redis:
#        condition: service_healthy
    stdin_open: true
    tty: true

#  worker:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    command: bash -c "bundle exec rails db:create db:migrate && bundle exec bin/jobs"
#    env_file:
#      - .env
#    environment:
#      RAILS_ENV: development
#      DATABASE_URL: postgres://postgres:postgres@db:5432/find_my_club_development
##      REDIS_URL: redis://redis:6379/0
#      RAILS_MAX_THREADS: 5
#    volumes:
#      - .:/rails
#      - bundle_cache:/usr/local/bundle
#      - rails_cache:/rails/tmp/cache
#    depends_on:
#      db:
#        condition: service_healthy
#      redis:
#        condition: service_healthy

#  css:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    command: bundle exec rails tailwindcss:watch
#    env_file:
#      - .env
#    environment:
#      RAILS_ENV: development
#    volumes:
#      - .:/rails
#      - bundle_cache:/usr/local/bundle
#    depends_on:
#      - web

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
  node_modules:
  rails_cache:
